### Get all handytools
GET http://localhost:8080/handytools
Accept: application/json

###

### Add a new handytool
POST http://localhost:8080/handytools
Content-Type: application/json

{
    "toolDetail": "cutter",
    "ownerName": "kt",
    "locationName": "office drawer",
    "borrowed": false,
    "borrowerName": null
}

###

### Add another handytool
POST http://localhost:8080/handytools
Content-Type: application/json

{
    "toolDetail": "drill",
    "ownerName": "kt",
    "locationName": "hanging at the barn's wall",
    "borrowed": false,
    "borrowerName": null
}

###

### Get a specific handytool by ID
GET http://localhost:8080/handytools/99
Accept: application/json

###

### Update a handytool by ID
PUT http://localhost:8080/handytools/1
Content-Type: application/json

{
    "toolDetail": "new tool name for #1",
    "ownerName": "kt",
    "locationName": "in the box under the desk",
    "borrowed": false,
    "borrowerName": null
}

###

### Delete a handytool by ID
DELETE http://localhost:8080/handytools/5
